language: c
arch:
     - amd64
     - ppc64le
compiler:
  - gcc
  - clang

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf automake debhelper dh-autoreconf devscripts fakeroot git-core libevent-dev

script:
  - ./autogen.sh &&
    mkdir build &&
    pushd build &&
    ../configure &&
    make &&
    make dist &&
    mv ocproxy*.tar.gz ../ &&
    popd &&
    ./build-debian.sh
