#!/bin/sh

#make an ecos epk from CVS lwIP

if test $EPK"" == "" ; then
	echo you must set the EPK environment var to the dir you want the EPK in
	exit;
fi

if test $LWIP_CVS"" == "" ; then
	echo you must set the LWIP_CVS  environment var to the dir you checked out the lwip module
	LWIP_CVS=../../../lwip;
	exit;
fi
EPK=$EPK/lwip_epk

#cleanup
rm -Rf $EPK


#copy files from CVS
xargs -n 2 ./copy  < files

#copy ecos specific files
cd ecos && find . ! -path '*CVS*' -a -type f -exec cp --parents {} $EPK \;
#make epk
cd $EPK && tar czf lwip.epk *

